/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.EjercicioBurguer;

/**
 *
 * @author retaz
 */
public class Ejercicio11Main extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio11Main
     */
    public Ejercicio11Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxHamburguesas = new javax.swing.JComboBox<>();
        jLabelSalsas = new javax.swing.JLabel();
        jComboBoxPan = new javax.swing.JComboBox<>();
        jLabelPan1 = new javax.swing.JLabel();
        jComboBoxPatatas = new javax.swing.JComboBox<>();
        jLabelBebida = new javax.swing.JLabel();
        jComboBoxBebida = new javax.swing.JComboBox<>();
        jRadioButtonHamburguesa = new javax.swing.JRadioButton();
        jRadioButtonDoble = new javax.swing.JRadioButton();
        jCheckBoxQueso = new javax.swing.JCheckBox();
        jCheckBoxPatatasExtra = new javax.swing.JCheckBox();
        jLabelPatatas1 = new javax.swing.JLabel();
        jLabelBebida1 = new javax.swing.JLabel();
        jRadioButtonRecogidaDomicilio = new javax.swing.JRadioButton();
        jLabelBebida2 = new javax.swing.JLabel();
        jRadioButtonRecogidaLocal = new javax.swing.JRadioButton();
        jLabelBebida3 = new javax.swing.JLabel();
        jTextFieldImporte = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSpinnerSalsasKetchup = new javax.swing.JSpinner();
        jSpinnerSalsasBarbacoa.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        LableKetchup = new javax.swing.JLabel();
        LabelBarbacoa = new javax.swing.JLabel();
        LabelMostaza = new javax.swing.JLabel();
        LabelThai = new javax.swing.JLabel();
        jSpinnerSalsasBarbacoa = new javax.swing.JSpinner();
        jSpinnerSalsasMostaza = new javax.swing.JSpinner();
        jSpinnerSalsasThai = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("HAMBURGUESA");

        jComboBoxHamburguesas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pollo", "Cerdo", "Ternera", "Vegana" }));

        jLabelSalsas.setBackground(new java.awt.Color(153, 153, 153));
        jLabelSalsas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalsas.setText("SALSAS");

        jComboBoxPan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Integral", "Centeno", " " }));
        jComboBoxPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPanActionPerformed(evt);
            }
        });

        jLabelPan1.setBackground(new java.awt.Color(153, 153, 153));
        jLabelPan1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPan1.setText("PAN");

        jComboBoxPatatas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fritas", "Gajo", "Caseras" }));

        jLabelBebida.setBackground(new java.awt.Color(153, 153, 153));
        jLabelBebida.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelBebida.setText("BEBIDA");

        jComboBoxBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Refreso de cola", "Refresco de naranja", "Refresco de limón", "Agua ", "Cerveza" }));

        buttonGroup1.add(jRadioButtonHamburguesa);
        jRadioButtonHamburguesa.setText("Simple");

        buttonGroup1.add(jRadioButtonDoble);
        jRadioButtonDoble.setText("Doble");

        jCheckBoxQueso.setText("Queso");

        jCheckBoxPatatasExtra.setText("Patatas extra");

        jLabelPatatas1.setBackground(new java.awt.Color(153, 153, 153));
        jLabelPatatas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPatatas1.setText("PATATAS");

        jLabelBebida1.setBackground(new java.awt.Color(153, 153, 153));
        jLabelBebida1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBebida1.setText("Recogida del local");

        buttonGroup2.add(jRadioButtonRecogidaDomicilio);

        jLabelBebida2.setBackground(new java.awt.Color(153, 153, 153));
        jLabelBebida2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBebida2.setText("Reparto a domicilio");

        buttonGroup2.add(jRadioButtonRecogidaLocal);

        jLabelBebida3.setBackground(new java.awt.Color(153, 153, 153));
        jLabelBebida3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelBebida3.setText("IMPORTE");

        jTextFieldImporte.setText("0");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSpinnerSalsasKetchup.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        LableKetchup.setText("Ketchup");

        LabelBarbacoa.setText("Barbacoa");

        LabelMostaza.setText("Mostaza");

        LabelThai.setText("Thai");

        jSpinnerSalsasBarbacoa.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinnerSalsasMostaza.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinnerSalsasThai.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelBebida2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonRecogidaDomicilio)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelBebida1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonRecogidaLocal))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabelPan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBoxHamburguesas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxPan, 0, 202, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelPatatas1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxPatatas, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelBebida3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextFieldImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonHamburguesa)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonDoble)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxQueso))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBoxPatatasExtra)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LableKetchup)
                                    .addComponent(LabelBarbacoa)
                                    .addComponent(LabelMostaza)
                                    .addComponent(LabelThai))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSpinnerSalsasKetchup)
                                    .addComponent(jSpinnerSalsasBarbacoa)
                                    .addComponent(jSpinnerSalsasMostaza)
                                    .addComponent(jSpinnerSalsasThai, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)))
                            .addComponent(jLabelSalsas, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxHamburguesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonHamburguesa)
                    .addComponent(jRadioButtonDoble)
                    .addComponent(jCheckBoxQueso))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerSalsasKetchup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LableKetchup))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSpinnerSalsasBarbacoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelBarbacoa)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPan1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSalsas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPatatas1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxPatatas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxPatatasExtra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelMostaza)
                            .addComponent(jSpinnerSalsasMostaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelThai)
                            .addComponent(jSpinnerSalsasThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBebida2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBebida1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jRadioButtonRecogidaDomicilio)
                    .addComponent(jRadioButtonRecogidaLocal))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBebida3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double precio=8.0;
        if (jComboBoxHamburguesas.getSelectedItem().equals("Ternera") ||jComboBoxHamburguesas.getSelectedItem().equals("Vegana")) precio+=1;
        if (jComboBoxPatatas.getSelectedItem().equals("Caseras")) precio+=1;
        if (jRadioButtonDoble.isSelected()) precio+=2;
        if (jCheckBoxQueso.isSelected()) precio+=0.5;
        if (jCheckBoxPatatasExtra.isSelected()) precio+=1;

        precio=precio+(0.5*(int)jSpinnerSalsasKetchup.getValue())+(0.5*(int)jSpinnerSalsasMostaza.getValue())+(0.5*(int)jSpinnerSalsasBarbacoa.getValue())+(0.5*(int)jSpinnerSalsasThai.getValue());
        precio=precio*1.21;
        if (jRadioButtonRecogidaLocal.isSelected()) precio=(precio-(precio*0.2));
        jTextFieldImporte.setText(String.valueOf(precio));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio11Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio11Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio11Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio11Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio11Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelBarbacoa;
    private javax.swing.JLabel LabelMostaza;
    private javax.swing.JLabel LabelThai;
    private javax.swing.JLabel LableKetchup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxPatatasExtra;
    private javax.swing.JCheckBox jCheckBoxQueso;
    private javax.swing.JComboBox<String> jComboBoxBebida;
    private javax.swing.JComboBox<String> jComboBoxHamburguesas;
    private javax.swing.JComboBox<String> jComboBoxPan;
    private javax.swing.JComboBox<String> jComboBoxPatatas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBebida;
    private javax.swing.JLabel jLabelBebida1;
    private javax.swing.JLabel jLabelBebida2;
    private javax.swing.JLabel jLabelBebida3;
    private javax.swing.JLabel jLabelPan1;
    private javax.swing.JLabel jLabelPatatas1;
    private javax.swing.JLabel jLabelSalsas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonDoble;
    private javax.swing.JRadioButton jRadioButtonHamburguesa;
    private javax.swing.JRadioButton jRadioButtonRecogidaDomicilio;
    private javax.swing.JRadioButton jRadioButtonRecogidaLocal;
    private javax.swing.JSpinner jSpinnerSalsasBarbacoa;
    private javax.swing.JSpinner jSpinnerSalsasKetchup;
    private javax.swing.JSpinner jSpinnerSalsasMostaza;
    private javax.swing.JSpinner jSpinnerSalsasThai;
    private javax.swing.JTextField jTextFieldImporte;
    // End of variables declaration//GEN-END:variables
}
